Feature/storyboard instantiate
Teamwork/swift-style-guide pull request #18
Opened 2018-11-14 17:20 UTC by denisq1991

Added a section on our storyboardInstatiate protocol as discussed in https://digitalcrew.teamwork.com/#tasks/12096245

2018-11-21 16:34 UTC, dfreniche requested changes
Some doubts to be cleared

2018-11-21 16:34 UTC, dfreniche commented on README.markdown
> +Once you've set this value you must simply call `instantiateFromMainStoryboard()` on the ViewController and the you will be returned an instance of that ViewController.
"and then you" --> typo?

2018-11-21 16:34 UTC, dfreniche commented on README.markdown
> +eg. `ProjectCollectionViewController.instantiateFromMainStoryboard()`
Where is `ProjectCollectionViewController.instantiateFromMainStoryboard` defined?

2018-11-21 17:03 UTC, rkreutz-teamwork commented on README.markdown
> +eg. `ProjectCollectionViewController.instantiateFromMainStoryboard()`
The protocol itself defines it. It's maaagic

2018-11-21 17:08 UTC, dfreniche commented on README.markdown
> +eg. `ProjectCollectionViewController.instantiateFromMainStoryboard()`
OK, thought it was something from Apple, now I see it's a function inside the protocol 👍

2018-11-29 08:37 UTC, josealobato approved these changes

2019-01-04 09:56 UTC, janodev approved these changes

2019-01-04 09:58 UTC, j4n0 commented
Approved, but there is a [typo](https://github.com/Teamwork/swift-style-guide/pull/18#discussion_r235443301).

2019-01-09 15:18 UTC, merged

2019-01-09 20:45 UTC, NSLeoFont commented
Please remove me from here...Receiving mails...Btw....Nice to meet you guys! Hope everything is going fine...All the best! Leo