Images plus Ray update
Teamwork/swift-style-guide pull request #24
Opened 2019-01-09 17:45 UTC by j4n0

Images section.
Manual update to changes in Ray Wenderlich 2019. Too many conflicts to be merged automatically.

2019-01-09 18:52 UTC, rkreutz-teamwork approved these changes

2019-01-10 10:27 UTC, denisq1991 commented on README.markdown
> +For functions with long signatures, put each parameter on a new line and add an extra indent on subsequent lines:
"long signature" is a bit ambiguous don't you think? We normally break a line for each parameter if the method signature includes more than two.

2019-01-10 10:28 UTC, denisq1991 commented on README.markdown
> +  translateConstant: Int, comment: String
Should `comment: String` be on a new line?

2019-01-10 10:56 UTC, denisq1991 approved these changes
Good stuff, thanks for updating all this @j4n0

2019-02-01 16:36 UTC, dfreniche requested changes
Address the few comments and merge this thing away!

2019-02-01 16:36 UTC, dfreniche commented on README.markdown
> +For functions with long signatures, put each parameter on a new line and add an extra indent on subsequent lines:
@denisq1991 I think that's exactly what @j4n0 refers to here: you break down a long function signature using newlines as per example below. The end result: you never have long signatures _in the same line_

2019-02-01 16:36 UTC, dfreniche commented on README.markdown
> +  translateConstant: Int, comment: String
@j4n0 yes, this should be in a new line

2019-02-01 16:36 UTC, dfreniche commented on README.markdown
>  ```
Superb

2019-02-02 16:20 UTC, merged