Adapting indentation and inter-method spaces
Teamwork/swift-style-guide pull request #26
Opened 2019-02-25 07:22 UTC by josealobato

2019-03-06 17:51 UTC, dfreniche requested changes
Just one minor change and good to go

2019-03-06 17:51 UTC, dfreniche commented on README.markdown
> +* There should be one blank lines between methods to help with separatation, visual clarity and organization. Lines with similar or connected behaviour should not be separated by empty newlines.  Whi
"There should be one blank __lines__" --> There should be one blank __line__

2019-03-19 11:01 UTC, denisq1991 commented on README.markdown
> +* There should be one blank lines between methods to help with separatation, visual clarity and organization. Lines with similar or connected behaviour should not be separated by empty newlines.  Whi
Nice catch, my only issue with the PR also

2019-03-19 11:01 UTC, denisq1991 approved these changes

2019-03-19 11:05 UTC, rkreutz-teamwork approved these changes

2019-03-22 13:04 UTC, merged