Update README with unit tests section
Teamwork/swift-style-guide pull request #4
Opened 2018-06-20 18:17 UTC by rkreutz-teamwork

2018-06-21 06:58 UTC, NSLeoFont requested changes

2018-06-21 06:58 UTC, NSLeoFont commented on README.markdown
> +    contex("When comparing two strings that are equal") {
It should be ```context``` not contex...

2018-06-21 14:02 UTC, rkreutz-teamwork commented on README.markdown
> +    contex("When comparing two strings that are equal") {
done 6fb62f7

2018-06-21 14:05 UTC, NSLeoFont approved these changes

2018-07-04 15:15 UTC, denisq1991 approved these changes

2018-07-04 16:43 UTC, dfreniche commented
@rkreutz-teamwork I've changed the base. Let's use master from now on

2018-07-09 10:20 UTC, chillok approved these changes

2018-07-09 11:13 UTC, merged